version: '3'
services:
    nginx-proxy:
      image: jwilder/nginx-proxy:alpine
      restart: always
      ports:
        - 80:80
        - 443:443
      volumes:
        - /etc/nginx/certs
        - /etc/nginx/vhost.d
        - /usr/share/nginx/html
        - /var/run/docker.sock:/tmp/docker.sock:ro
      labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    citytrip_apache:
        build: .docker/apache
        container_name: citytrip_sf4_apache
        environment:
          VIRTUAL_HOST: citytrip.trifall.net,citytrip,citytrip.urenapi.nl, localhost
          VIRTUAL_PORT: 80
        expose:
          - 80
        ports:
          - 8085:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - citytrip_php
        restart: always

    citytrip_mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: citytrip_sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: city_trip_api
            MYSQL_USER: CityTrip
            MYSQL_PASSWORD: CityTrip
        restart: always
        ports:
          - 33061:3306

    citytrip_php:
        build: .docker/php
        container_name: citytrip_sf4_php
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          - maildev_host=citytrip_sf4_maildev
        depends_on:
          - citytrip_maildev
          - citytrip_mysql
        restart: always

    citytrip_phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: citytrip_sf4_phpmyadmin
        environment:
          PMA_HOST: citytrip_mysql
          PMA_PORT: 3306
          PMA_USER: root
          PMA_PASSWORD: root
        ports:
            - 8081:80
        links:
            - citytrip_mysql
        restart: always

    citytrip_maildev:
        image: djfarrelly/maildev
        container_name: citytrip_sf4_maildev
        ports:
          - 8002:80
        restart: always
