version: '3'
services:
    apache:
        build: .docker/apache
        container_name: citytrip_sf4_apache
        environment:
          - VIRTUAL_HOST= citytrip.trifall.net
        expose:
          - 80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php
        restart: always

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: citytrip_sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: city_trip_api
            MYSQL_USER: CityTrip
            MYSQL_PASSWORD: CityTrip
        restart: always
        ports:
          - 33061:3306

    php:
        build: .docker/php
        container_name: citytrip_sf4_php
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - mysql
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: citytrip_sf4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8081:80
        links:
            - mysql
        restart: always

    maildev:
        image: djfarrelly/maildev
        container_name: citytrip_sf4_maildev
        ports:
          - 8002:80
        restart: always
